spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reserva
    username: reserva
    password: reserva
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.cuscatlan.reserva: INFO
