spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/reserva
    username: reserva
    password: reserva
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.cuscatlan.reserva: DEBUG
